# =========================
# SKI RESORT SIMULATION CONFIG
# Based on Val Thorens, France
# =========================

# SIMULATION SIZE
NUM_VISITORS = 20

# VISITOR TYPES
VISITOR_TYPES = ["skier", "snowboarder"]

# ARRIVAL PATTERN
ARRIVAL_INTERVAL_MIN = 0.1
ARRIVAL_INTERVAL_MAX = 0.5

# RENTAL SHOP
NUM_SKIS = 45
NUM_SNOWBOARDS = 30
RENTAL_STAFF = 4
RENTAL_TIME_MIN = 1.5
RENTAL_TIME_MAX = 3.0

# LIFT SYSTEM
NUM_LIFTS = 3
LIFT_CAPACITY = 6
LIFT_RIDE_TIME_MIN = 2.0
LIFT_RIDE_TIME_MAX = 4.0

# SLOPES
NUM_SLOPES = 5
SLOPE_CAPACITY = 20
SLOPE_TIME_MIN = 3.0
SLOPE_TIME_MAX = 6.0
FALL_CHANCE = 0.08
FALL_DELAY = 2.0

# CAFE / LODGE
CAFE_SEATS = 25
CAFE_STAFF = 3
CAFE_VISIT_CHANCE = 0.35
CAFE_TIME_MIN = 2.0
CAFE_TIME_MAX = 5.0

# VISITOR BEHAVIOR
MIN_RUNS_PER_VISITOR = 2
MAX_RUNS_PER_VISITOR = 6
STARTING_ENERGY = 100
ENERGY_LOSS_PER_RUN_SKIER = 12
ENERGY_LOSS_PER_RUN_SNOWBOARDER = 15
ENERGY_GAIN_CAFE = 25
LEAVE_ENERGY_THRESHOLD = 25

# OUTPUTS TO TRACK
TRACK_WAIT_TIMES = True
TRACK_QUEUE_LENGTHS = True
TRACK_SLOPE_RUNS = True
TRACK_CAFE_VISITS = True
TRACK_FALLS = True