# SKI RESORT SIMULATION CONFIG
# Based on Val Thorens, France


# SIMULATION SIZE
NUM_VISITORS = 80

# VISITOR TYPES
VISITOR_TYPES = ["skier", "snowboarder"]

# ARRIVAL PATTERN
ARRIVAL_INTERVAL_MIN = 0.08
ARRIVAL_INTERVAL_MAX = 0.25

# RENTAL SHOP
NUM_SKIS = 50
NUM_SNOWBOARDS = 40
RENTAL_STAFF = 6
RENTAL_TIME_MIN = 1.0
RENTAL_TIME_MAX = 2.0

# LIFT SYSTEM
NUM_LIFTS = 2
LIFT_CAPACITY = 4
LIFT_RIDE_TIME_MIN = 1.5
LIFT_RIDE_TIME_MAX = 2.5

# SLOPES
NUM_SLOPES = 3
SLOPE_CAPACITY = 25
SLOPE_TIME_MIN = 2.0
SLOPE_TIME_MAX = 4.0
FALL_CHANCE = 0.05
FALL_DELAY = 1.0

# CAFE / LODGE
CAFE_SEATS = 30
CAFE_STAFF = 6
CAFE_VISIT_CHANCE = 0.22
CAFE_TIME_MIN = 1.0
CAFE_TIME_MAX = 2.2

# VISITOR BEHAVIOR
MIN_RUNS_PER_VISITOR = 2
MAX_RUNS_PER_VISITOR = 6
STARTING_ENERGY = 100
ENERGY_LOSS_PER_RUN_SKIER = 12
ENERGY_LOSS_PER_RUN_SNOWBOARDER = 15
ENERGY_GAIN_CAFE = 25
LEAVE_ENERGY_THRESHOLD = 25

# OUTPUTS TO TRACK
TRACK_WAIT_TIMES = True
TRACK_QUEUE_LENGTHS = True
TRACK_SLOPE_RUNS = True
TRACK_CAFE_VISITS = True
TRACK_FALLS = True

# PEAK ARRIVAL PERIOD
PEAK_START_VISITOR = 20
PEAK_END_VISITOR = 45
PEAK_ARRIVAL_INTERVAL_MIN = 0.03
PEAK_ARRIVAL_INTERVAL_MAX = 0.10