# SKI RESORT SIMULATION CONFIG
# Based on Val Thorens, France

# SIMULATION SIZE
NUM_VISITORS = 250

# VISITOR TYPES
VISITOR_TYPES = ["skier", "snowboarder"]

# ARRIVAL PATTERN
ARRIVAL_INTERVAL_MIN = 0.06
ARRIVAL_INTERVAL_MAX = 0.18

# RENTAL SHOP
NUM_SKIS = 150
NUM_SNOWBOARDS = 130
RENTAL_STAFF = 14
RENTAL_TIME_MIN = 0.6
RENTAL_TIME_MAX = 1.3

# LIFT SYSTEM
NUM_LIFTS = 8
LIFT_CAPACITY = 8
LIFT_RIDE_TIME_MIN = 0.7
LIFT_RIDE_TIME_MAX = 1.3

# SLOPES
NUM_SLOPES = 3
SLOPE_CAPACITY = 55
SLOPE_TIME_MIN = 1.2
SLOPE_TIME_MAX = 2.2
FALL_CHANCE = 0.05
FALL_DELAY = 0.6

# VISITOR BEHAVIOR
MIN_RUNS_PER_VISITOR = 2
MAX_RUNS_PER_VISITOR = 4
STARTING_ENERGY = 100
ENERGY_LOSS_PER_RUN_SKIER = 14
ENERGY_LOSS_PER_RUN_SNOWBOARDER = 17
ENERGY_GAIN_CAFE = 25
LEAVE_ENERGY_THRESHOLD = 35

# OUTPUTS TO TRACK
TRACK_WAIT_TIMES = True
TRACK_QUEUE_LENGTHS = True
TRACK_SLOPE_RUNS = True
TRACK_CAFE_VISITS = True
TRACK_FALLS = True

# PEAK ARRIVAL PERIOD
PEAK_START_VISITOR = 70
PEAK_END_VISITOR = 150
PEAK_ARRIVAL_INTERVAL_MIN = 0.05
PEAK_ARRIVAL_INTERVAL_MAX = 0.12
PEAK_SERVICE_SLOWDOWN_FACTOR = 1.05

# CAFE / LODGE
CAFE_SEATS = 50
CAFE_STAFF = 9
CAFE_VISIT_CHANCE = 0.25
CAFE_TIME_MIN = 0.6
CAFE_TIME_MAX = 1.3